package model;

public enum ErrorCode {
    ORDER_CREATION_FAILED,
    PRODUCT_CREATION_FAILED,
    BUYER_CREATION_FAILED,
    PRODUCT_ALREADY_CREATED,
    IN_SUFFICIENT_INVENTORY,
    PIN_CODE_UNSERVICEABLE;
}
